version: 2
jobs:
  build-test:
    working_directory: ~/temp/
    machine:
      image: circleci/classic:latest
      
    steps:
      - checkout
      - run: 
          name: Install prerequisites
          command: cd Scripts/ && chmod 755 installCiPrerequisites.sh && ./installCiPrerequisites.sh
      - run:
          name: Building Docker Demo Api project
          command: cd DockerDemoApi/ && dotnet restore ./DockerDemoApi.sln && dotnet build ./DockerDemoApi.sln
      - run:
          name: Run Specs db
          command: cd Scripts/ && chmod 755 startCiSpecsDb.sh && ./startCiSpecsDb.sh
      - run:
          name: Running tests
          command: cd DockerDemoApi/DockerDemoApi.Specs/ && dotnet test

  deploy-job:
    working_directory: ~/temp/
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: 
          name: Install prerequisites
          command: cd Scripts/ && chmod 755 installCiDeploymentPrerequisites.sh && ./installCiDeploymentPrerequisites.sh
      - run:
          name: Create new production image
          command: cd Dockerfiles/Production && chmod 755 createProductionImage.sh && ./createProductionImage.sh
      - run:
          name: Push to docker hub
          command: docker login -u="$DOCKERUSERNAME" -p="$DOCKERPASSWORD" && docker push mswarbrick/dockerdemoapi:prod

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only: master
      - deploy-job:
          requires:
            - build-test

