version: 2
jobs:
  build:
    working_directory: /temp

    docker:
      - image: microsoft/aspnetcore-build:1.0-2.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Building Docker Demo Api project
          command: cd DockerDemoApi/ && dotnet restore ./DockerDemoApi.sln && dotnet build ./DockerDemoApi.sln

