version: 2
jobs:
  build-test:
    working_directory: ~/temp/
    machine:
      image: circleci/classic:latest
      
    steps:
      - checkout
      - run: 
          name: Install prerequisites
          command: cd Scripts/ && chmod 755 installCiPrerequisites.sh && ./installCiPrerequisites.sh
      - run:
          name: Building Docker Demo Api project
          command: cd DockerDemoApi/ && dotnet restore ./DockerDemoApi.sln && dotnet build ./DockerDemoApi.sln
      - run:
          name: Run Specs db
          command: cd Scripts/ && chmod 755 startCiSpecsDb.sh && ./startCiSpecsDb.sh
      - run:
          name: Running tests
          command: cd DockerDemoApi/DockerDemoApi.Specs/ && dotnet test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only: master

