version: '2.3'
services:
  mssql:
    image: microsoft/mssql-server-windows-developer:2017-GA
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1Strongpassword!"
      ACCEPT_EULA: "Y"

  initdb:
    image: microsoft/mssql-server-windows-developer:2017-GA
    container_name: initdb
    depends_on:
      mssql: 
        condition: service_healthy
    volumes:
      - .\Scripts:C:\Scripts
    working_dir: \Scripts
    command: Powershell.exe -executionpolicy remotesigned -File SetUpDevDb.ps1

  webapp:
    image: microsoft/aspnetcore:2.0
    container_name: webapp
    depends_on:
      initdb:
        condition: service_started
    volumes:
        - .\Scripts:C:\Scripts
        - .\publish:C:\app
    working_dir: \Scripts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5555:80"
    command: Powershell.exe -executionpolicy remotesigned -File RunWebApp.ps1

networks:
  default:
    external:
      name: nat